FuelTypes = {
    1 : 'Unleaded Petrol',
    2 : 'Premium Unleaded',
    4 : 'Diesel',
    5 : 'LPG',
    6 : '98 RON',
    10 : 'E85',
    11 : 'Brand diesel',
}
    
FuelBrands = {
    '29' : '7-Eleven',
    '2' : 'Ampol',
    '3' : 'Better Choice',
    '4' : 'BOC',
    '5' : 'BP',
    '6' : 'Caltex',
    '19' : 'Caltex Woolworths',
    '20' : 'Coles Express',
    '32' : 'Costco',
    '24' : 'Eagle',
    '25' : 'FastFuel 24/7',
    '7' : 'Gull',
    '15' : 'Independent',
    '8' : 'Kleenheat',
    '9' : 'Kwikfuel',
    '10' : 'Liberty',
    '30' : 'Metro Petroleum',
    '11' : 'Mobil',
    '13' : 'Peak',
    '26' : 'Puma',
    '14' : 'Shell',
    '23' : 'United',
    '27' : 'Vibe',
    '31' : 'WA Fuels',
    '16' : 'Wesco',
}

Regions = {
    '25' : 'Metro : North of River',
    '26' : 'Metro : South of River',
    '27' : 'Metro : East/Hills',
    '15' : 'Albany',
    '28' : 'Augusta / Margaret River',
    '30' : 'Bridgetown / Greenbushes',
    '1' : 'Boulder',
    '2' : 'Broome',
    '16' : 'Bunbury',
    '3' : 'Busselton (Townsite)',
    '29' : 'Busselton (Shire)',
    '19' : 'Capel',
    '4' : 'Carnarvon',
    '33' : 'Cataby',
    '5' : 'Collie',
    '34' : 'Coolgardie',
    '35' : 'Cunderdin',
    '31' : 'Donnybrook / Balingup',
    '36' : 'Dalwallinu',
    '6' : 'Dampier',
    '20' : 'Dardanup',
    '37' : 'Denmark',
    '38' : 'Derby',
    '39' : 'Dongara',
    '7' : 'Esperance',
    '40' : 'Exmouth',
    '41' : 'Fitzroy Crossing',
    '17' : 'Geraldton',
    '21' : 'Greenough',
    '22' : 'Harvey',
    '42' : 'Jurien',
    '8' : 'Kalgoorlie',
    '43' : 'Kambalda',
    '9' : 'Karratha',
    '44' : 'Kellerberrin',
    '45' : 'Kojonup',
    '10' : 'Kununurra',
    '18' : 'Mandurah',
    '32' : 'Manjimup',
    '58' : 'Meckering',
    '46' : 'Meekatharra',
    '47' : 'Moora',
    '48' : 'Mt Barker',
    '61' : 'Munglinup',
    '23' : 'Murray',
    '11' : 'Narrogin',
    '49' : 'Newman',
    '50' : 'Norseman',
    '60' : 'North Bannister',
    '12' : 'Northam',
    '62' : 'Northam (Shire)',
    '13' : 'Port Hedland',
    '51' : 'Ravensthorpe',
    '57' : 'Regans Ford',
    '14' : 'South Hedland',
    '53' : 'Tammin',
    '24' : 'Waroona',
    '54' : 'Williams',
    '55' : 'Wubin',
    '59' : 'Wundowie',
    '56' : 'York',
}

StateRegions = {
    '1' : 'Gascoyne',
    '2' : 'Goldfields-Esperance',
    '3' : 'Great Southern',
    '4' : 'Kimberley',
    '5' : 'Mid-West',
    '6' : 'Peel',
    '7' : 'Pilbara',
    '8' : 'South-West',
    '9' : 'Wheatbelt',
    '98' : 'Metro',
}